# Generated by Django 3.1.3 on 2020-11-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ambulance_fire_police'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
