# Generated by Django 3.1.3 on 2020-11-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
