# Generated by Django 3.1.3 on 2020-11-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ambulance_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fire',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='police',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
