# Generated by Django 3.1.3 on 2020-11-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201112_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='patient_problem',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
